In [1]:
import torch

torch.__version__

'2.13.0+cu130'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [11]:
MATRIX = torch.tensor([
    [19,20],
    [20,30]])

MATRIX

tensor([[19, 20],
        [20, 30]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.8878, 0.7659, 0.4608, 0.4711],
         [0.5342, 0.9469, 0.3085, 0.8101],
         [0.9339, 0.2196, 0.5930, 0.0639]]),
 torch.float32)

In [23]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
zeros = torch.zeros(size=(3,4),dtype=int)
zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [26]:
ones = torch.ones(size=(3,4))

ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [28]:
zero_to_ten_deprecated = torch.range(0,10)

zero_to_ten = torch.arange(start=0,end=10, step=2)

zero_to_ten,zero_to_ten_deprecated

/tmp/ipykernel_485215/3360097484.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


(tensor([0, 2, 4, 6, 8]),
 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [30]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [31]:
float_32_tensor = torch.tensor(
    [3.0,6.0,9.0], dtype=None,
    device=None,
    requires_grad=False
)


float_32_tensor.dtype, float_32_tensor.shape,float_32_tensor.device

(torch.float32, torch.Size([3]), device(type='cpu'))

In [32]:
float_16_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f'shape {some_tensor.shape}')
print(f'Dtype {some_tensor.dtype}')

tensor([[0.5578, 0.7964, 0.0215, 0.5033],
        [0.7507, 0.7378, 0.0316, 0.9297],
        [0.7869, 0.4216, 0.8165, 0.9773]])
shape torch.Size([3, 4])
Dtype torch.float32


In [36]:
tensor = torch.tensor([1,2,3])

tensor + 10, tensor *10, tensor/10

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([0.1000, 0.2000, 0.3000]))

In [37]:
tensor

tensor([1, 2, 3])

In [39]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [40]:
tensor * tensor

tensor([1, 4, 9])

In [42]:
a=torch.matmul(tensor,tensor)
a

tensor(14)

In [45]:
torch.matmul(tensor,torch.tensor([10,1,2]))

tensor(18)

In [46]:
tensor @ tensor

tensor(14)

# Exercise

In [47]:
tensor_rand = torch.rand(7,7)
tensor_rand

tensor([[0.7226, 0.6652, 0.2863, 0.3382, 0.0090, 0.4752, 0.6344],
        [0.3399, 0.2884, 0.7964, 0.9174, 0.6763, 0.5897, 0.5318],
        [0.7949, 0.6087, 0.5012, 0.8128, 0.6219, 0.6381, 0.6881],
        [0.8315, 0.0630, 0.1570, 0.3334, 0.5787, 0.7246, 0.3738],
        [0.7669, 0.0654, 0.0139, 0.6254, 0.1770, 0.0075, 0.4703],
        [0.8883, 0.3243, 0.0544, 0.3328, 0.9353, 0.2960, 0.2340],
        [0.5433, 0.4168, 0.5244, 0.7473, 0.5798, 0.9528, 0.8732]])

In [48]:
tensor_rand_1 = torch.rand(1,7)
tensor_rand_1

tensor([[0.0622, 0.5253, 0.8698, 0.1588, 0.8243, 0.6304, 0.5493]])

In [ ]:
tensor_rand @ tensor_rand_1.T


tensor([[1.3525],
        [2.2323],
        [2.2270],
        [1.4135],
        [0.6024],
        [1.4118],
        [2.3858]])

In [52]:
torch.matmul(tensor_rand,tensor_rand_1.T)

tensor([[1.3525],
        [2.2323],
        [2.2270],
        [1.4135],
        [0.6024],
        [1.4118],
        [2.3858]])

In [58]:
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)

tensor_A = torch.rand(7,7)
torch.random.manual_seed(seed=RANDOM_SEED) 
tensor_B = torch.rand(1,7)
torch.random.manual_seed(seed=RANDOM_SEED) 
tensor_C = torch.rand(7,7)
print("Tensor A \n", tensor_A)

print("Tensor B \n", tensor_B)

print("Tensor C \n", tensor_C)

tensor_A @ tensor_B.T

Tensor A 
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Tensor B 
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
Tensor C 
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [59]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [60]:
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [61]:
RANDOM_SEED = 1234

In [78]:

torch.cuda.manual_seed(1234)

torch.manual_seed(1234)
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)


tensor_A_gpu = tensor_A.to(device)

tensor_B_gpu = tensor_B.to(device)
tensor_A_gpu,tensor_B_gpu

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [ ]:
ans = tensor_A_gpu @ tensor_B_gpu.T
ans



tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [86]:
torch.max(ans), torch.min(ans), torch.argmax(ans), torch.argmin(ans)

(tensor(0.5617, device='cuda:0'),
 tensor(0.3647, device='cuda:0'),
 tensor(3, device='cuda:0'),
 tensor(0, device='cuda:0'))

In [92]:
torch.manual_seed(7)
tensor_r = torch.rand(1,1,1,10)
tensor_r_1 = torch.squeeze(tensor_r)



print(f"Tensor: {tensor_r}")
print(f"Shape: {tensor_r.shape}")

print(f"\nSqueezed tensor: {tensor_r_1}")
print(f"Squeezed shape: {tensor_r_1.shape}")


Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape: torch.Size([1, 1, 1, 10])

Squeezed tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed shape: torch.Size([10])
